### ISSUE TITLE
Apply NR to blank fields on vrMIS forms

### ISSUE THREAD

**Issue by Pranjalita** [OpenLMIS/open-lmis#26]
As a User
I should be able to click on 'Apply NR to blank fields' button on vrMIS forms 
So that it becomes easy to fill the form

1.Login as username: fieldCoordinator and password: User123
2.Go to 'Distributions' menu tab.
3.Select a Delivery Zone ,program and period from the dropdowns.
4.Then click on 'Initiate Distribution' button.
5.Select a Facility and click on for example 'Epi Inventory' menu tab to navigate to Epi Inventory form. 

CURRENT SCENARIO:
When we fill some of the values, and the form is partially filled. 
Then only way to make unfilled fields not recorded is to click individual NR checkboxes.

ACCEPTANCE CRITERIA:
Click on 'Apply NR to blank fields' ----> NR checkboxes for unfilled fields would be checked, textboxes for unfilled fields would be disabled, form status icon turns green.

**Comment by joshzamor** [comment]
Closing this issue as this was completed in the 1.0 branch.
