### ISSUE TITLE
Upgrade Spring version

### ISSUE THREAD

**Issue by mananbharara** [OpenLMIS/open-lmis#29]
The task involves upgrading the Spring version including spring-webmvc, spring beans, spring-web and spring-integration for all modules of openlmis.

Dependency file: {project_dir}/modules/{module_name}/build.gradle

Current version: 3.1.1
Latest stable: 4.0.1

The upgraded build should be able to pass all functional specs and unit tests

**Comment by joshzamor** [comment]
Closing this issue as Spring was upgraded to 4+ as part of the "2.0" branch.
